import numpy as np
import sqlite3
import os
from multiprocessing import Pool
from numpy_sqlite3 import *

database_name = '/work/lyang_umass_edu/projectedColumns-main/coldens_1e%d_TF%.1f.db'

sqlite3.register_adapter(np.ndarray, adapt_array)
sqlite3.register_converter("array", convert_array)

def mkdir(path):#if the path does not exist, then create a new path; if it does exist, then do nothing
	folder = os.path.exists(path)
	if not folder:
		os.makedirs(path, exist_ok=True)

def read_projection(field, conn, ion, background, direction, run_name, timeNum):
    cursor = conn.cursor()
    cursor.execute('SELECT %s FROM proj WHERE (ion = ? AND background = ? AND direction = ? AND run_name = ? and timeNum = ?)' % field,\
         (ion, background, direction, run_name, timeNum))
    data = cursor.fetchone()[0]
    cursor.close()
    return data

def read_colden(conn, ion, background, direction, run_name, timeNum):
    #cunn: a sqlite3.Connection object connected to the database used
    return read_projection('coldens', conn, ion, background, direction, run_name, timeNum)

def read_width(conn, ion, background, direction, run_name, timeNum):
    #cunn: a sqlite3.Connection object connected to the database used
    width_thermal = read_projection('width_thermal', conn, ion, background, direction, run_name, timeNum)
    width_kinematic = read_projection('width_doppler', conn, ion, background, direction, run_name, timeNum) #1/sqrt(2) times the real kinematic broadening
    return np.sqrt(width_thermal ** 2 + 2 * width_kinematic ** 2)


def extract_projections(background_value, direction, run, width=False):
    #Convert the .db files generated by makeColDens_db.py to text files
    ion_list = ['H I 1215', 'He II', 'C II', 'C III', 'C IV', 'O IV', 'O VI', 'O VII', 'O VIII', 'Ne VIII', 'Mg II', 'Si II', 'Si III', 'Si IV']
    header = '%d,H I 1215, He II, C II, C III, C IV, O IV, O VI, O VII, O VIII, Ne VIII, Mg II, Si II, Si III, Si IV'
    #TF_list = [1.0, 2.0, 3.0]
    TF_list = [1.0]
    timeNum = 3
    background = 'HM_1e%d' % background_value
    #print(run)
    #print(direction)
    for i in range(len(TF_list)):
        temp_floor = TF_list[i]

        save_path = '/work/lyang_umass_edu/nonSorted_ColDen/Projection_Database/Projections/%s/%s/TF%.1f/' % (run, background, temp_floor)
        mkdir(save_path)

        database = database_name % (background_value, temp_floor)
        conn = sqlite3.connect(database, detect_types=sqlite3.PARSE_DECLTYPES)
        colden_list = []
        width_list = []
        for ion in ion_list:
            #print(ion)
            colden_list.append(read_colden(conn, ion, background, direction, run, timeNum))
            if width == True:
                width_list.append(read_width(conn, ion, background, direction, run, timeNum))
        
        colden_list.insert(0, np.arange(len(colden_list[0])))
        colden_list = np.array(colden_list)
        colden_list = colden_list.transpose()
        if i == 0:
            useful_pixels = np.where(colden_list[:, 5] > 1e12)[0]#choose pixels with N(CIV)>1e10
        output_colden = colden_list[useful_pixels, :]

        if width == True:
            width_list.insert(0, np.arange(len(width_list[0])))
            width_list = np.array(width_list)
            width_list = width_list.transpose()
            output_width = np.nan_to_num(width_list[useful_pixels])
        
        filename = save_path + run + '_colden_%d.csv' % (10 * direction)
        fmt = ['%d']
        fmt.extend(['%.5e'] * len(ion_list))
        np.savetxt(filename, output_colden, fmt=fmt, delimiter=',', header=header % np.shape(output_colden)[0], comments='')
        
        if width == True:
            filename = save_path + run + '_width_%d.csv' % (10 * direction)
            fmt = ['%d']
            fmt.extend(['%.5e'] * len(ion_list))
            np.savetxt(filename, output_width, fmt=fmt, delimiter=',', header=header % np.shape(output_colden)[0], comments='')

def main(direction):
    #background_values = [0, 1, 2, 3, 4, 5, 6, 7]
    background_values = [4]
    TF_list = [1.0]
    run_list = ['T0.3_v1000_chi300', 'T0.3_v1000_chi300_cond']
    #temporary: take the average of HM_1e2 and HM_1e4 results for HM_1e3

    for run in run_list:
        for background_value in background_values:
            print(run, direction, background_value)
            extract_projections(background_value, direction, run, width=True)

if __name__ == '__main__':
    #direction_list = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    direction_list = [1.0]
    
    #with Pool(len(direction_list)) as p:
    #    p.map(main, direction_list)
    main(0.0)
    main(1.0)

