import numpy as np
import sqlite3
import os
from multiprocessing import Pool
from mpi4py import MPI
import yt
from numpy_sqlite3 import *
from gen_aux_data_athenapk import _blob

comm = MPI.COMM_WORLD
nprocs = comm.Get_size()
rank   = comm.Get_rank()

database = '/nas/astro-th/lyang/projectedColumns-main/data_bases/coldens_blob0.5_athenapk.db'

sqlite3.register_adapter(np.ndarray, adapt_array)
sqlite3.register_converter("array", convert_array)

run1 = { 'Name':'T0.3_v1700_chi300',
         'Formal_name':'T0.3_v1700_chi300_old',
         'Snapshot_name':'KH_hdf5_chk_%04d',
        'Dir':'/nas/astro-th/lyang/GiantDrive1/Blob_paper1/Files/',
        'Mach':6.5,
        'tcc':1.0,
        'velocity':1700,
        'f_list':['0022', '0032', '0053', '0085'],
        'f_list_full':sorted(set(['%04d' % i for i in range(106)[: : 5]] + ['0022', '0032', '0053', '0085']))}

run2 = { 'Name':'T0.3_v1700_chi300_cond',
         'Formal_name':'T0.3_v1700_chi300_cond_old',
         'Snapshot_name':'KH_hdf5_chk_%04d',
        'Dir':'/nas/astro-th/lyang/GiantDrive1/Blob_paper2/Files/',
        'Mach':6.5,
        'tcc':1.0,
        'velocity':1700,
        'f_list':['0003', '0020', '0046', '0078'],
        'f_list_full':['0003', '0020', '0046', '0078']}

run3 = { 'Name':'cloud_chi300beta100v1700transcond',
         'Formal_name':'T0.3_v1700_chi300_beta100_transcond',
         'Snapshot_name':'parthenon.restart.%05d.rhdf',
        'Dir':'/nas/astro-th/lyang/',
        'Mach':6.5,
        'tcc':1.0,
        'velocity':1700,
        'f_list':['00003', '00020', '00039', '00050'],
        'f_list_full':['%05d' % i for i in range(51)]}

runlist = []
runlist.append(run3)

def mkdir(path):#if the path does not exist, then create a new path; if it does exist, then do nothing
	folder = os.path.exists(path)
	if not folder:
		os.makedirs(path, exist_ok=True)

def read_projection(field, conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift):
    cursor = conn.cursor()
    cursor.execute('SELECT %s FROM proj WHERE (ion = ? AND background = ? AND direction = ? AND blob_cut = ? AND temp_floor = ? AND run_name = ? and timeNum = ? and redshift = ?)' % field,\
         (ion, background, str(direction), str(blob_cut), str(temp_floor), run_name, timeNum, str(redshift)))
    data = cursor.fetchone()[0]
    cursor.close()
    return data

def read_colden(conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift):
    #cunn: a sqlite3.Connection object connected to the database used
    return read_projection('coldens', conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift)

def read_width(conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift):
    #cunn: a sqlite3.Connection object connected to the database used
    width_thermal = read_projection('width_thermal', conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift)
    width_kinematic = read_projection('width_doppler', conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift) #1/sqrt(2) times the real kinematic broadening
    return width_thermal, width_kinematic


def extract_projections(background_value, direction, run, blob_cut, redshift, width=False):
    #Convert the .db files generated by makeColDens_db.py to text files
    ion_list = ['H I 1215', 'He II', 'C II', 'C III', 'C IV', 'O IV', 'O VI', 'O VII', 'O VIII', 'Ne VIII', 'Mg II', 'Si II', 'Si III', 'Si IV', 'N V']
    header = '%d,H I 1215, He II, C II, C III, C IV, O IV, O VI, O VII, O VIII, Ne VIII, Mg II, Si II, Si III, Si IV, N V'
    TF_list = [0.6]
    run_name = run['Name']
    directory = run['Dir']
    #TF_list = [1.0]
    timeNum_list = list(range(4))
    #timeNum_list = [2]
    background = 'HM_1e%d' % background_value
    projection_base = '/nas/astro-th/lyang/nonSorted_ColDen_23/blob%g/%s/' % (blob_cut, run_name)

    cloud_file = projection_base + 'cloud_data.txt'

    if 'ld' in run_name:
        init_cloud_mass = 1.99e38 * yt.units.g
    else:
        init_cloud_mass = 1.23067e38 * yt.units.g

    if direction == 0.0 and background_value == 0:
        mkdir(projection_base)
        with open(cloud_file, 'w') as f:
            f.write('# %d\n' % len(timeNum_list))
            for timeNum in timeNum_list:
                data = yt.load(directory + run_name + '/parthenon.restart.%s.rhdf' % run['f_list'][timeNum])
                data.add_field(('parthenon','blob'), function=_blob, sampling_type='cell', display_name=r'$C_{\mathrm{cloud}}$', units='dimensionless')
                allDataRegion = data.all_data()
                cloudRegion = allDataRegion.cut_region(['obj["blob"] >= %g' % blob_cut])
                mcloud = (cloudRegion.quantities.total_mass()[0] / init_cloud_mass).value
                vol_cloud = np.sum((cloudRegion['gas', 'cell_volume']) / (1 * yt.units.pc**3).value) #in pc^3

                density_cloud = (cloudRegion['gas', 'density'] / (1 * yt.units.g / yt.units.cm ** 3)).value
                head_density = np.percentile(density_cloud, 99)
                f.write('%.5f %.5e %.5e\n' % (mcloud, vol_cloud, head_density))

    #print(run_name)
    #print(direction)
    for timeNum in timeNum_list:
        for i in range(len(TF_list)):
            temp_floor = TF_list[i]
            save_path = projection_base + '%s/TF%.1f/z%g/t%d/' % (background, temp_floor, redshift, timeNum)
            mkdir(save_path)

            #print(database)
            conn = sqlite3.connect(database, detect_types=sqlite3.PARSE_DECLTYPES)
            colden_list = []
            width_list = []
            thermal_width_list = []
            kinematic_width_list = []
            for ion in ion_list:
                #print(ion)
                colden_list.append(read_colden(conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift))
                if width == True:
                    thermal_width, kinematic_width = read_width(conn, ion, background, direction, blob_cut, temp_floor, run_name, timeNum, redshift)
                    thermal_width = np.nan_to_num(thermal_width)
                    kinematic_width = np.nan_to_num(kinematic_width)

                    thermal_width_list.append(thermal_width)
                    kinematic_width_list.append(kinematic_width)
                    width_list.append(np.sqrt(thermal_width ** 2 + 2 * kinematic_width ** 2))
            
            colden_list.insert(0, np.arange(len(colden_list[0])))
            colden_list = np.array(colden_list)
            colden_list = colden_list.transpose()
            if i == 0:
                useful_pixels = np.any(colden_list[:, 2:] > 1e9, axis=1)#choose pixels with N(CIV)>1e10
            output_colden = colden_list[useful_pixels, :]

            if width == True:
                thermal_width_list.insert(0, np.arange(len(thermal_width_list[0])))
                thermal_width_list = np.array(thermal_width_list)
                thermal_width_list = thermal_width_list.transpose()
                output_thermal_width = thermal_width_list[useful_pixels]
                
                kinematic_width_list.insert(0, np.arange(len(kinematic_width_list[0])))
                kinematic_width_list = np.array(kinematic_width_list)
                kinematic_width_list = kinematic_width_list.transpose()
                output_kinematic_width = kinematic_width_list[useful_pixels]

                width_list.insert(0, np.arange(len(width_list[0])))
                width_list = np.array(width_list)
                width_list = width_list.transpose()
                output_width = width_list[useful_pixels]
            
            filename = save_path + run_name + '_colden_%d.csv' % (10 * direction)
            fmt = ['%d']
            fmt.extend(['%.5e'] * len(ion_list))
            np.savetxt(filename, output_colden, fmt=fmt, delimiter=',', header=header % np.shape(output_colden)[0], comments='')
            
            if width == True:
                filename = save_path + run_name + '_width_%d.csv' % (10 * direction)
                fmt = ['%d']
                fmt.extend(['%.5e'] * len(ion_list))
                np.savetxt(filename, output_width, fmt=fmt, delimiter=',', header=header % np.shape(output_colden)[0], comments='')

                filename = save_path + run_name + '_thermal_width_%d.csv' % (10 * direction)
                fmt = ['%d']
                fmt.extend(['%.5e'] * len(ion_list))
                np.savetxt(filename, output_thermal_width, fmt=fmt, delimiter=',', header=header % np.shape(output_colden)[0], comments='')

                filename = save_path + run_name + '_kinematic_width_%d.csv' % (10 * direction)
                fmt = ['%d']
                fmt.extend(['%.5e'] * len(ion_list))
                np.savetxt(filename, output_kinematic_width, fmt=fmt, delimiter=',', header=header % np.shape(output_colden)[0], comments='')

if __name__ == '__main__':
    #direction_list = [0.0, 1.0]
    direction_list = [0.0, 1.0, 0.5, 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9]
    #direction_list = [0.0]
    #background_values = np.arange(8)
    background_values = [0]
    #background_values = [-100]
    blob_cut_list = [0.5]
    #blob_cut_list = [0.82]
    #redshift_list = [0.1006, 0.5396]
    #redshift_list = [0.5396]
    redshift_list = [0.5396]
    #temporary: take the average of HM_1e2 and HM_1e4 results for HM_1e3
		
    if nprocs % len(direction_list) != 0:
        print('number of processes has to be an integral multiple of %d' % len(direction_list))
        exit(0)

    background_start = int(rank / len(direction_list))
    background_gap = int(nprocs / len(direction_list))
    if background_start >= len(background_values):
        exit(0)

    direction = direction_list[rank % len(direction_list)]
    for redshift in redshift_list:
        for run in runlist:
            for background_value in background_values[background_start::background_gap]:
                for blob_cut in blob_cut_list:
                    print(redshift, run['Name'], direction, background_value, blob_cut)
                    extract_projections(background_value, direction, run, blob_cut, redshift, width=True)
